### ISSUE TITLE
“Request a new exhibit” button design fail

### ISSUE THREAD

**Issue by atz** [sul-dlss/portfolios#10]
“Request a new exhibit” button that tells me I need a SUNET login, even when I am already logged in. 

Then when I click on it, it tells me: "You are not authorized to access this page."
- Don't give the user useless prompts.  
- Don't give the user bogus links.

**Comment by ggeisler** [comment]
I believe this was fixed months ago in the Exhibits code: https://github.com/sul-dlss/exhibits/issues/212 / https://github.com/sul-dlss/exhibits/pull/239/files
